spring:
  application:
    name: 'fornecedor'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fornecedor
    password: root
    username: root
    
    
  jpa:
    hibernate:
      ddl-auto: update
