spring:
  application:
    name: 'loja'
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loja
    password: root
    username: root
    
    
  jpa:
    hibernate:
      ddl-auto: update
