spring:
  application:
    name: 'loja'
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/loja
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
